// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebAppApi.Models;

namespace WebAppApi.Data
{
    public partial interface Imy_brandContextProcedures
    {
        Task<int> backupAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<getcategoryResult>> getcategoryAsync(int? cat_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> user_updateAsync(int? user_id, string user_name, string login_name, string user_password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
