// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppApi.Models
{
    public partial class BillDetailsTb
    {
        public int? BillId { get; set; }
        public int? CatId { get; set; }
        public string Note { get; set; }
        public decimal? Total { get; set; }
        public int? UserId { get; set; }

        public virtual BillsTb Bill { get; set; }
        public virtual CategoriesTb Cat { get; set; }
        public virtual UserTb User { get; set; }
    }
}