// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppApi.Models
{
    public partial class BillsTb
    {
        public int BillId { get; set; }
        public DateTime? BillDate { get; set; }
        public string BillType { get; set; }
        public int? ClientId { get; set; }

        public virtual ClientTb Client { get; set; }
    }
}