// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppApi.Models
{
    public partial class CategoriesTb
    {
        public CategoriesTb()
        {
            CatRmTbs = new HashSet<CatRmTb>();
        }

        public int CatId { get; set; }
        public string CatName { get; set; }
        public string StoreDate { get; set; }
        public int? Quentity { get; set; }
        public int? StoreId { get; set; }
        public decimal? Price { get; set; }

        public virtual Store Store { get; set; }
        public virtual ICollection<CatRmTb> CatRmTbs { get; set; }
    }
}