// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppApi.Models
{
    public partial class CategoreisWithAmount
    {
        public int CatId { get; set; }
        public string CatName { get; set; }
        public decimal? SaleAmount { get; set; }
    }
}