// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppApi.Models
{
    public partial class CatRmTb
    {
        public int CatId { get; set; }
        public int RmId { get; set; }
        public string Note { get; set; }

        public virtual CategoriesTb Cat { get; set; }
        public virtual RowMaterialsTb Rm { get; set; }
    }
}