// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppApi.Models
{
    public partial class ClientTb
    {
        public ClientTb()
        {
            BillsTbs = new HashSet<BillsTb>();
            ClientBalanceTbs = new HashSet<ClientBalanceTb>();
        }

        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string City { get; set; }

        public virtual ICollection<BillsTb> BillsTbs { get; set; }
        public virtual ICollection<ClientBalanceTb> ClientBalanceTbs { get; set; }
    }
}