// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppApi.Models
{
    public partial class ClientDeleted
    {
        public int ClientId { get; set; }
        public string ClientName { get; set; }
    }
}