// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppApi.Models
{
    public partial class ClientBalanceTb
    {
        public int ClientBalanceId { get; set; }
        public int? ClientId { get; set; }
        public int? CurrencyId { get; set; }
        public decimal? Balance { get; set; }

        public virtual ClientTb Client { get; set; }
        public virtual CurrencyTb Currency { get; set; }
    }
}