// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppApi.Models
{
    public partial class CurrencyTb
    {
        public CurrencyTb()
        {
            ClientBalanceTbs = new HashSet<ClientBalanceTb>();
            StoreBalanceTbs = new HashSet<StoreBalanceTb>();
        }

        public int CurrencyId { get; set; }
        public string CurrencyName { get; set; }

        public virtual ICollection<ClientBalanceTb> ClientBalanceTbs { get; set; }
        public virtual ICollection<StoreBalanceTb> StoreBalanceTbs { get; set; }
    }
}