// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAppApi.Models
{
    public partial class getcategoryResult
    {
        public string cat_name { get; set; }
    }
}
