// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppApi.Models
{
    public partial class RoleTb
    {
        public RoleTb()
        {
            UserRoleTbs = new HashSet<UserRoleTb>();
        }

        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public byte? RoleState { get; set; }

        public virtual ICollection<UserRoleTb> UserRoleTbs { get; set; }
    }
}