// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppApi.Models
{
    public partial class RowMaterialsTb
    {
        public RowMaterialsTb()
        {
            CatRmTbs = new HashSet<CatRmTb>();
        }

        public int RmId { get; set; }
        public string RmName { get; set; }
        public int? Quentity { get; set; }
        public int? StoreId { get; set; }

        public virtual Store Store { get; set; }
        public virtual ICollection<CatRmTb> CatRmTbs { get; set; }
    }
}