// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppApi.Models
{
    public partial class Store
    {
        public Store()
        {
            CategoriesTbs = new HashSet<CategoriesTb>();
            RowMaterialsTbs = new HashSet<RowMaterialsTb>();
            StoreBalanceTbs = new HashSet<StoreBalanceTb>();
        }

        public int StoreId { get; set; }
        public string StoreName { get; set; }
        public string Location { get; set; }

        public virtual ICollection<CategoriesTb> CategoriesTbs { get; set; }
        public virtual ICollection<RowMaterialsTb> RowMaterialsTbs { get; set; }
        public virtual ICollection<StoreBalanceTb> StoreBalanceTbs { get; set; }
    }
}