// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppApi.Models
{
    public partial class UserBill
    {
        public string UserName { get; set; }
        public int? BillId { get; set; }
    }
}